# Dongle mode
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# 3 profiles (n+2)
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# Combo config
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=7

CONFIG_I2C=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_IDLE_TIMEOUT=300000

# Prospector Display ZMK Module
# CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
# CONFIG_PROSPECTOR_FIXED_BRIGHTESS=80
# CONFIG_PROSPECTOR_PROSPECTOR_ROTATE_DISPLAY_180=y
# CONFIG_PROSPECTOR_LAYER_ROLLER_ALL_CAPS=y