manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: carrefinho
      url-base: https://github.com/carrefinho
    - name: tokyo2006
      url-base: https://github.com/tokyo2006
    - name: urob
      url-base: https://github.com/urob
    - name: shortlurker
      url-base: https://github.com/shortlurker
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    #- name: zmk
    #  remote: petejohanson
    #  revision: feat/pointers-with-input-processors
    #  import: app/west.yml
    ## Modules ##
    - name: cirque-input-module
      remote: petejohanson
      revision: main
    - name: zmk-auto-layer
      remote: urob
      revision: main
    - name: prospector-zmk-module
      remote: shortlurker
      revision: nice_nano
  self:
    path: config
    