manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: carrefinho
      url-base: https://github.com/carrefinho
    - name: shortlurker
      url-base: https://github.com/shortlurker
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    ## Modules ##
    #- name: zmk-auto-layer
    #  remote: urob
    #  revision: main
    - name: prospector-zmk-module
      remote: shortlurker
      revision: nice_nano
  self:
    path: config
